### ISSUE TITLE
CMake Error: The source directory "<path_to_folder>/amazon-freertos/build" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by TaLucGiaHoang** [andestech/amazon-freertos#4] opened 2020-10-09 07:40 UTC
**Describe the bug**
I am following this document [Corvette-F1_UM168_V1.4_bpm_AWS.pdf](https://github.com/andestech/amazon-freertos/blob/master/vendors/andes/boards/corvette_f1_n25/Getting_Started_Guide_Corvette-F1_N25.pdf) to build aws_freertos demo for andes. At the section **Generate Build Files for Your Demo Project and Build the Demo** get the following error:
```
$ cd <amazon-freertos directory>
$ cmake -DVENDOR=andes -DBOARD=corvette_f1_n25 -DAFR_IS_TESTING=0 -DCOMPILER=riscv32-elf -B build
CMake Error: The source directory "<amazon-freertos directory>/amazon-freertos/build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

```
Could you please help me solve this issue.
Thank you!

**Comment by kevinwang821020** [comment] 2020-11-12 02:26
Hi, @TaLucGiaHoang 
I am sorry for replying so late.
For your question, i can't reproduce you situation.
Please follow the step below:
1. $ git clone https://github.com/andestech/amazon-freertos.git
2. $ cd  amazon-freertos
3. $ cmake -DVENDOR=andes -DBOARD=corvette_f1_n25 -DAFR_IS_TESTING=0 -DCOMPILER=riscv32-elf -B build

Then, you will see the following message:
...
...
==============================================
-- Configuring done
-- Generating done
-- Build files have been written to: /home/kevin/amazon-freertos/build

Please check again.
If you still can't build, please give me more information, like the actually command you type from the first step to the end.

Thank you.

**Comment by TaLucGiaHoang** [comment] 2020-11-23 04:24
Hi @kevinwang821020 
Thanks for your replying. I have fixed my issue. I met this issue because of extracting Cygwin.tar.gz failed. I had used 7-zip GUI software to extract Cygwin.tar.gz and nds32le-elf-newlib-v5.txz, that fail to extract some files.

To fix it I used command line to extract:
```
$ tar xvf Cygwin.tar.gz
```
and
```
$ tar xvf nds32le-elf-newlib-v5.txz
```

**Comment by kevinwang821020** [comment] 2020-11-25 01:52
I am grade to hear you figure out the problem.

Thank you for your question.
If you have any problem in the future, please let us know.

"The bug has been clarified, so close this issue"

**Closed as completed by kevinwang821020** 2020-11-25 01:52 UTC
Labels: bug
